fix: ci fails with lint issue

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -30,8 +30,13 @@ jobs:
         run: cargo install scarb-cairo-lint --git https://github.com/keep-starknet-strange/cairo-lint
 
       - uses: asdf-vm/actions/install@v3
-      - run: scarb cairo-lint
-      - run: scarb cairo-lint --fix
+      - name: Run cairo-lint
+        run: |
+          scarb cairo-lint > lint_output.txt
+          if grep -q "warning:" lint_output.txt; then
+            echo "Linting failed due to warnings"
+            exit 1
+          fi
 
   test:
     runs-on: ubuntu-latest
